seed: 2222
clean: 6
debug: False
train: True
result: evaluate  # evaluate, instance_numbers, sagittalcenters
load_directory: /home/phalendj/code/rsna2024/outputs/2024-09-23/13-33-15/ # /home/phalendj/code/rsna2024/outputs/2024-09-23/10-35-04/ # /home/phalendj/code/rsna2024/outputs/2024-09-20/18-15-46/ # For reloads
mode: valid

directories:
  relative_directory: /data/phalendj/kaggle/rsna2024
  image_directory: train_images
dataset:
  name: SegmentationPredictedCenterDataset
  image_size:
  - 512
  - 512
  series_description: Sagittal T2/STIR
  conditions:
  - Spinal Canal Stenosis
  channels: 15
  aug_size: 0.10
  center_file: /data/phalendj/kaggle/rsna2024/train_label_coordinates.csv
  augmentations:
    prob: 0.75
    normalize: true
    hflip: false
    contrast: true
    blur: true
    blur_limit: 9
    noise: True
    downscale: True
    distort: False
    rotate: False
    crop:
      use: false
      size: 512
    channel_shuffle: false
    sharpen: false
loss:
  # name: InstanceLevelCrossEntropy  
  # name: HeatmapLoss
  # patch_size: 512
  name: WeightedCrossEntropy

model:
  name: magic
  # model_name: densenet121
  # model_name: pvt_v2_b2
  model_name: tf_efficientnetv2_b2.in1k
  nclasses: 3
  num_layers: 4
  bottleneck_layers: 4
  num_points: 5
  dropout: 0.1
  
optimization:
  optimizer: AdamW
  learning_rate: 1.0e-4
  weight_decay: 1.e-2

  # scheduler: CosineWithWarmup
  # n_cycles: 0.475

  scheduler: MultiStepLR
  milestones: [5, 10]
  gamma: 0.1

training:
  use_folds: [0, 1, 2, 3, 4]
  # use_folds: [2]
  use_amp: True
  epochs: 15
  batch_size: 8
  grad_acc: 1
  early_stopping: 5
  workers: 12