seed: 2222


directories:
  relative_directory: /data/phalendj/kaggle/rsna2024
  image_directory: train_images


dataset:
  name: SegmentationSingleImageDataset
  image_size: [512, 512]
  series_description: Sagittal T2/STIR
  conditions: ['Spinal Canal Stenosis']
  aug_size: 0.1
  

loss:
  name: HeatmapLoss
  patch_size: 512

model:
  name: unet
  model_name: densenet201
  encodername: resnet18
  channels: 1
  unet_classes: 5
  nclasses: 15
  patch_size: 512

optimization:
  optimizer: AdamW
  scheduler: CosineWithWarmup
  learning_rate: 1.e-4
  weight_decay: 1.e-2
  n_cycles: 0.475

training:
  use_folds: [0, 1, 2, 3, 4]
  use_amp: True
  epochs: 10
  batch_size: 32
  grad_acc: 1
  early_stopping: 3
  workers: 12

