seed: 2222
clean: 6
debug: false
train: true
result: evaluate
load_directory: null
mode: valid
directories:
  relative_directory: /data/phalendj/kaggle/rsna2024
  image_directory: train_images
dataset:
  name: LevelCubeLeftRightAreaDataset
  image_size:
  - 512
  - 512
  series_description: Sagittal T1
  conditions:
  - Left Neural Foraminal Narrowing
  - Right Neural Foraminal Narrowing
  channels: 11
  subsize: 224
  d_side: 50
  aug_size: 0.1
  center_file: /data/phalendj/kaggle/rsna2024/train_label_coordinates.csv
  augmentations:
    prob: 0.75
    normalize: true
    hflip: false
    contrast: true
    blur: true
    blur_limit: 9
    noise: true
    downscale: true
    distort: true
    rotate: true
    crop:
      use: false
      size: 512
    channel_shuffle: false
    sharpen: false
loss:
  name: WeightedCrossEntropy
model:
  name: tdcnnlevelside2
  model_name: densenet121
  nclasses: 3
  num_layers: 4
  subsize: 64
  dropout: 0.1
optimization:
  optimizer: AdamW
  learning_rate: 0.0001
  weight_decay: 0.01
  scheduler: MultiStepLR
  milestones:
  - 5
  - 10
  gamma: 0.1
training:
  use_folds:
  - 0
  - 1
  - 2
  - 3
  - 4
  use_amp: true
  epochs: 15
  batch_size: 6
  grad_acc: 1
  early_stopping: 5
  workers: 12
